### ISSUE TITLE
How to create an auto upload image url with this?

### ISSUE THREAD

**Issue by cesarvarela** [cloudinary/cloudinary-js-base#419]
Hi, I'm looking at how to create this but using this library, instead of hardcoding it like this:

```
   const cloudinaryUrl = `https://res.cloudinary.com/${cloudName}/image/upload/${mapping}/${publicID}`;
```

**Comment by aleksandar-cloudinary** [comment]
Hi @cesarvarela , Thanks for reaching out.

We have examples of how you can build URLs to your assets using this library in the following section of the documentation:
https://cloudinary.com/documentation/javascript2_image_transformations#deliver_and_transform_images
For auto-upload specifically, since the mapping is a folder or folders, that is already part of the `public_id` and that can be passed to the dedicated SDK method. For example, `const sample_img_url = cld.image("test/sample.jpg").toURL();` will give a URL similar to the one you shared for the [sample.jpg](https://res.cloudinary.com/demo/image/upload/sample.jpg) but if it was inside the "test" folder.

Please try this out and let me know if you run into any issues. You can find the installation steps here: https://cloudinary.com/documentation/javascript2_quick_start#1_install_packages

**Comment by cesarvarela** [comment]
Hi, thanks, I understand now.

Suggestion: maybe add some util to avoid having to make string manipulation to get the id?
